import QRCode from 'qrcode';
import { Card } from '@/components/ui';
import type { MovePass } from '@/lib/types';

/**
 * The tenant's move-in pass, the way a cinema ticket works.
 *
 * Rendered to SVG on the server: a QR is a static image, so shipping a
 * generator to the browser to draw one would be a bundle for nothing — and it
 * means the pass is on screen the instant the page paints, which matters when
 * somebody is holding their phone up at a doorway.
 *
 * The owner scans this. It exists only here, on the tenant's own device, which
 * is what stops an owner collecting on a tenant who never turned up.
 */
export async function MoveInPass({ pass }: { pass: MovePass }) {
  const svg = await QRCode.toString(pass.token, {
    type: 'svg',
    errorCorrectionLevel: 'M',
    margin: 1,
    // Pure black on transparent, then recoloured by CSS so the code stays
    // scannable in dark mode instead of inverting into a grey-on-grey mess.
    color: { dark: '#000000', light: '#00000000' },
  });

  if (pass.used) {
    return (
      <Card className="mb-4">
        <p className="eyebrow mb-2">Move-in pass</p>
        <p className="text-sm">
          Used. You are checked in — nothing more to show at the door.
        </p>
      </Card>
    );
  }

  return (
    <Card className="mb-4">
      <p className="eyebrow mb-1">Move-in pass</p>
      <p className="mb-5 text-sm text-[var(--text-muted)]">
        Show this at {pass.propertyName} when you arrive. The PG scans it, and only then is
        your money passed on to them.
      </p>

      <div className="flex flex-col items-center">
        {/*
          White plate under the code regardless of theme. Scanners want dark on
          light, and a QR sitting straight on a dark background often will not
          read at all.
        */}
        <div
          className="rounded-[var(--radius-card)] bg-white p-4 shadow-[var(--shadow-card)] [&>svg]:block [&>svg]:size-44 sm:[&>svg]:size-52"
          // Generated by us from our own token, not user input rendered as markup.
          dangerouslySetInnerHTML={{ __html: svg }}
        />

        <div className="mt-5 text-center">
          <p className="text-xs text-[var(--text-muted)]">Or read out this code</p>
          <p className="figure mt-1 text-3xl font-semibold tracking-[0.2em]">{pass.shortCode}</p>
        </div>

        <dl className="mt-5 flex gap-6 text-center text-sm">
          <div>
            <dt className="text-xs text-[var(--text-muted)]">Room</dt>
            <dd className="figure font-semibold">{pass.roomCode}</dd>
          </div>
          <div>
            <dt className="text-xs text-[var(--text-muted)]">Bed</dt>
            <dd className="figure font-semibold">{pass.bedCode}</dd>
          </div>
        </dl>
      </div>
    </Card>
  );
}
